[build]
  publish = "."
  command = "echo 'Serving static HTML file'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/test.html"
  status = 200

[dev]
  command = "node server.js"
  port = 3000
  publish = "." 