[build]
  publish = "dist"
  command = "bash build.sh"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "node server.js"
  port = 3000
  publish = "." 